wandb_version: 1

resume:
  desc: null
  value: allow
architecture:
  desc: null
  value: wav2vec_v2_v4
dataset:
  desc: null
  value: RAVDESS_audio_speech
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 50
initial_epoch:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0005
dropout_rate:
  desc: null
  value: 0.4
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.42.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721135521
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.11.9
      5: 0.17.4
      6: 4.42.4
      8:
      - 4
      - 5
      13: darwin-arm64
